```java
package com.labs;

public class Book {

    // Stores the unique ID of the book
    private int bookID;

    // Stores the title of the book
    private String title;

    // Stores the total number of copies sold
    private int totalQuantitySold;

    // Stores the price of one copy of the book
    private double price;

    // Stores the total revenue generated by the book
    private double totalRevenue;

    // Constructor used to create a new Book object
    public Book(int bookID, String title, int quantitySold, double price) {

        // Sets the book ID
        this.bookID = bookID;

        // Sets the book title
        this.title = title;

        // Sets the initial quantity sold
        this.totalQuantitySold = quantitySold;

        // Sets the price per book
        this.price = price;

        // Calculates the initial total revenue
        this.totalRevenue = quantitySold * price;
    }

    // Adds additional sales to the book's existing totals
    public void aggregateQty(int quantity) {

        // Adds the new quantity to the total quantity sold
        totalQuantitySold += quantity;

        // Adds the revenue from the new sales to the total revenue
        totalRevenue += quantity * price;
    }

    // Returns the book's ID
    public int getBookID() {
        return bookID;
    }

    // Returns the book's title
    public String getTitle() {
        return title;
    }

    // Returns the total quantity of books sold
    public int getTotalQuantitySold() {
        return totalQuantitySold;
    }

    // Returns the price of one book
    public double getPrice() {
        return price;
    }

    // Returns the total revenue for the book
    public double getTotalRevenue() {
        return totalRevenue;
    }
}
```
